export const project_single_schema = {
  type: "object",
  properties: {
    status: { type: "number" },
    message: { type: "string" },
    data: [
      {
        id: { type: "number" },
        projectId: { type: "number" },
        version: { type: "number" },
        serviceType: { type: "string" },
        reviseFor: { type: "number" },
        reviseForNumber: { type: "string" },
        origin: { type: "number" },
        revisionNumber: { type: "number" },
        number: { type: "string" },
        date: { type: "string" },
        employeeRelationOfficer: { type: "string" },
        clientUserName: { type: "string" },
        clientUserContactNumber: { type: "string" },
        clientUserEmail: { type: "string" },
        poNumber: { type: "string" },
        poDate: { type: "string" },
        contractDateStart: { type: "string" },
        contractDateEnd: { type: "string" },
        clientHeaderId: { type: "number" },
        clientHeaderName: { type: "string" },
        clientDetailIdForBillingAddress: { type: "number" },
        clientDetailNameForBillingAddress: { type: "string" },
        clientDetailAddressForBilling: { type: "string" },
        clientContactId: { type: "number" },
        clientContactName: { type: "string" },
        clientContactNumber: { type: "string" },
        clientContactEmail: { type: "string" },
        invoiceNeedPO: { type: "boolean" },
        invoiceNeedTimesheet: { type: "boolean" },
        invoiceTimesheetPeriod: { type: "string" },
        invoiceNeedBAST: { type: "boolean" },
        rateType: { type: "string" },
        overtimeChargedToCustomer: { type: "boolean" },
        termsOfPayment: { type: "number" },
        clientContactIdForInvoicing: { type: "number" },
        clientContactNameForInvoicing: { type: "string" },
        clientContactNumberForInvoicing: { type: "string" },
        clientContactEmailForInvoicing: { type: "string" },
        projectLocation: { type: "string" },
        overtimeIncentive: { type: "string" },
        overtimeModel: { type: "number" },
        laptopIncentive: { type: "string" },
        toolProviderModel: { type: "number" },
        otherIcentive: { type: "string" },
        workingHourStart: { type: "string" },
        workingHourEnd: { type: "string" },
        workingHour: { type: "string" },
        note: { type: "string" },
        salesUserId: { type: "string" },
        approval1: { type: "string" },
        approval2: { type: "string" },
        approval3: { type: "string" },
        approval4: { type: "string" },
        approval5: { type: "string" },
        approval1Status: { type: "string" },
        approval2Status: { type: "string" },
        approval3Status: { type: "string" },
        approval4Status: { type: "string" },
        approval5Status: { type: "string" },
        approval1Note: { type: "string" },
        approval2Note: { type: "string" },
        approval3Note: { type: "string" },
        approval4Note: { type: "string" },
        approval5Note: { type: "string" },
        approval1Date: { type: "string" },
        approval2Date: { type: "string" },
        approval3Date: { type: "string" },
        approval4Date: { type: "string" },
        approval5Date: { type: "string" },
        needApproval: { type: "number" },
        needApprovalBy: { type: "string" },
        lastApprovalStatus: { type: "string" },
      },
    ],
  },
};

export const project_all_schema = {
  type: "array",
  items: project_single_schema,
};

export const pcaItem_single_schema = {
  type: "object",
  properties: {
    status: { type: "number" },
    message: { type: "string" },
    data: [
      {
        projectCostingId: { type: "number" },
        contractDateStart: { type: "string" },
        contractDateEnd: { type: "string" },
        itemNumber: { type: "number" },
        itemNumberDisplay: { type: "number" },
        itemName: { type: "string" },
        roleDisplay: { type: "string" },
        manpowerSolutionOpportunityId: { type: "number" },
        note: { type: "string" },
        personId: { type: "number" },
        salaryGrade: { type: "number" },
        cost: { type: "number" },
        sellPrice: { type: "number" },
        grossProfit: { type: "number" },
        grossProfitPercentage: { type: "number" },
        subItems: [
          {
            projectCostingId: { type: "number" },
            itemNumber: { type: "number" },
            subItemName: { type: "string" },
            urut: { type: "number" },
            grade: { type: "string" },
            unit: { type: "string" },
            unitDisplay: { type: "string" },
            quantity: { type: "number" },
            period: { type: "number" },
            periodActual: { type: "number" },
            unitSellPrice: { type: "number" },
            sellPrice: { type: "number" },
            sellPriceActual: { type: "number" },
            unitCost: { type: "number" },
            cost: { type: "number" },
            costActual: { type: "number" },
            unitGrossProfit: { type: "number" },
            grossProfit: { type: "number" },
            grossProfitActual: { type: "number" },
            grossProfitPercentage: { type: "number" },
            grossProfitPercentageActual: { type: "number" },
          },
        ],
      },
    ],
  },
};

export const pcaItem_all_schema = {
  type: "array",
  items: pcaItem_single_schema,
};

export const pcaSubItem_single_schema = {
  type: "object",
  properties: {
    status: { type: "number" },
    message: { type: "string" },
    data: [
      {
        projectCostingId: { type: "number" },
        itemNumber: { type: "number" },
        subItemName: { type: "string" },
        urut: { type: "number" },
        grade: { type: "string" },
        unit: { type: "string" },
        unitDisplay: { type: "string" },
        quantity: { type: "number" },
        period: { type: "number" },
        periodActual: { type: "number" },
        unitSellPrice: { type: "number" },
        sellPrice: { type: "number" },
        sellPriceActual: { type: "number" },
        unitCost: { type: "number" },
        cost: { type: "number" },
        costActual: { type: "number" },
        unitGrossProfit: { type: "number" },
        grossProfit: { type: "number" },
        grossProfitActual: { type: "number" },
        grossProfitPercentage: { type: "number" },
        grossProfitPercentageActual: { type: "number" },
      },
    ],
  },
};

export const pcaSubItem_all_schema = {
  type: "array",
  items: pcaSubItem_single_schema,
};

export const pcaSubItemAll_single_schema = {
  type: "object",
  properties: {
    status: { type: "number" },
    message: { type: "string" },
    data: [
      {
        projectCostingId: { type: "number" },
        itemNumber: { type: "number" },
        subItemName: { type: "string" },
        grade: { type: "string" },
        unit: { type: "string" },
        unitDisplay: "string",
        quantity: { type: "number" },
        period: { type: "number" },
        unitSellPrice: { type: "number" },
        sellPrice: { type: "number" },
        unitCost: { type: "number" },
        cost: { type: "number" },
        unitGrossProfit: { type: "number" },
        grossProfit: { type: "number" },
        grossProfitPercentage: { type: "number" },
        itemNumberDisplay: { type: "number" },
        itemName: { type: "string" },
        roleDisplay: { type: "string" },
        manpowerSolutionOpportunityId: { type: "number" },
        note: { type: "string" },
        personId: { type: "number" },
        salaryGrade: { type: "number" },
        subtotalCost: { type: "number" },
        subtotalSellPrice: { type: "number" },
        subtotalGrossProfit: { type: "number" },
        subtotalGrossProfitPercentage: { type: "number" },
      },
    ],
  },
};

export const pcaSupport_single_schema = {
  type: "object",
  properties: {
    status: { type: "number" },
    message: "string",
    data: [
      {
        projectCostingId: { type: "number" },
        attachmentId: { type: "number" },
        fileName: { type: "string" },
        description: { type: "string" },
      },
    ],
  },
};

export const pcaSupport_all_schema = {
  type: "array",
  items: pcaSupport_single_schema,
};
